default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: detect-private-key


  - repo: https://github.com/psf/black
    rev: 23.12.0
    hooks:
      - id: black
        args: [ "--line-length=100" ]
        language_version: python3.11
