version: 2.1


orbs:
  python: circleci/python@2.1.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip

      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install ruff codespell flake8 responses pytest mypy

      - run:
          name: Run tests
          command: python -m pytest


      - run:
          name: Linting - Flake8, Ruff, codespell
          command: |
            flake8 ./summedia/ --output-file test-reports
            codespell ./summedia/
            ruff --output-format=github --target-version=py310 --line-length=100 ./summedia/


workflows:
  sample:
    jobs:
      - build-and-test
